name: SME-Serap-Acompanhamento-Worker
 
on:

  workflow_dispatch:

jobs:
         
  build-dev:

    runs-on: self-hosted
    if: ${{ github.ref == 'refs/heads/dev' }}
    steps:
      - uses: actions/checkout@v2
      
      -  name: Github
         shell: bash
         env:
          gituser: ${{ secrets.GIT_USER }}
          gittoken: ${{ secrets.GIT_TOKEN }}
         run: |
              git clone https://$gituser:$gittoken@github.com/julianocm/SME-Serap-Acompanhamento-Worker.git --branch=develop
      
      -  name: Login to registry
         uses: docker/login-action@v1
         with:
          registry: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PWD }}
    
      - name: Build the Docker image Backend  
        run: |
             cd SME-Serap-Acompanhamento-Worker
             docker login ${{ secrets.REGISTRY_HOST }}
             docker build -f src/SME.SERAp.Prova.Acompanhamento.Worker/Dockerfile --tag ${{ secrets.REGISTRY_HOST }}/develop/serap-acompanhamento-worker .
             docker push ${{ secrets.REGISTRY_HOST }}/develop/serap-acompanhamento-worker

  build-hom:

    runs-on: self-hosted
    if: ${{ github.ref == 'refs/heads/hom' }}
    steps:
      - uses: actions/checkout@v2
      
      -  name: Github
         shell: bash
         env:
          gituser: ${{ secrets.GIT_USER }}
          gittoken: ${{ secrets.GIT_TOKEN }}
         run: |
              git clone https://$gituser:$gittoken@github.com/julianocm/SME-Serap-Acompanhamento-Worker.git --branch=release
      
      -  name: Login to registry
         uses: docker/login-action@v1
         with:
          registry: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PWD }}
    
      - name: Build the Docker image Backend  
        run: |
             cd SME-Serap-Acompanhamento-Worker
             docker login ${{ secrets.REGISTRY_HOST }}
             docker build -f src/SME.SERAp.Prova.Acompanhamento.Worker/Dockerfile --tag ${{ secrets.REGISTRY_HOST }}/release/serap-acompanhamento-worker .
             docker push ${{ secrets.REGISTRY_HOST }}/release/serap-acompanhamento-worker

  build-dev:

    runs-on: self-hosted
    if: ${{ github.ref == 'refs/heads/dev' }}
    steps:
      - uses: actions/checkout@v2
      
      -  name: Github
         shell: bash
         env:
          gituser: ${{ secrets.GIT_USER }}
          gittoken: ${{ secrets.GIT_TOKEN }}
         run: |
              git clone https://$gituser:$gittoken@github.com/julianocm/SME-Serap-Acompanhamento-Worker.git --branch=develop
      
      -  name: Login to registry
         uses: docker/login-action@v1
         with:
          registry: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PWD }}
    
      - name: Build the Docker image Backend  
        run: |
             cd SME-Serap-Acompanhamento-Worker
             docker login ${{ secrets.REGISTRY_HOST }}
             docker build -f src/SME.SERAp.Prova.Acompanhamento.Worker/Dockerfile --tag ${{ secrets.REGISTRY_HOST }}/develop/serap-acompanhamento-worker .
             docker push ${{ secrets.REGISTRY_HOST }}/develop/serap-acompanhamento-worker
             
  deploy-prod:
  
    runs-on: self-hosted
    needs: [ build-prod ]
    if: ${{ github.ref == 'refs/heads/prod' }}
    environment:
      name: production
    steps:
      - name: Redeploy
        uses: luizhpriotto/action_images@kubectl-v2.0
        env: 
          RANCHER_URL: ${{ secrets.RANCHER_URL }}
          RANCHER_TOKEN: ${{ secrets.RANCHER_TOKEN }}
          WORKLOAD: serap-acompanhamento-worker
          NAMESPACE: sme-serap-acompanhamento
          
  deploy-dev:
  
    runs-on: self-hosted
    needs: [ build-dev ]
    if: ${{ github.ref == 'refs/heads/dev' }}
    environment:
      name: development
    steps:
      - name: Redeploy
        uses: luizhpriotto/action_images@kubectl-v2.0
        env: 
          RANCHER_URL: ${{ secrets.RANCHER_URL }}
          RANCHER_TOKEN: ${{ secrets.RANCHER_TOKEN }}
          WORKLOAD: serap-acompanhamento-worker
          NAMESPACE: sme-serap-acompanhamento
          
  deploy-hom:
  
    runs-on: self-hosted
    needs: [ build-hom ]
    if: ${{ github.ref == 'refs/heads/hom' }}
    environment:
      name: release
    steps:
      - name: Redeploy
        uses: luizhpriotto/action_images@kubectl-v2.0
        env: 
          RANCHER_URL: ${{ secrets.RANCHER_URL }}
          RANCHER_TOKEN: ${{ secrets.RANCHER_TOKEN }}
          WORKLOAD: serap-acompanhamento-worker
          NAMESPACE: sme-serap-acompanhamento
