name: SME-Limpeza-App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    container:
      image: docker://cirrusci/flutter:1.22.5
      
    steps:
      -  name: Gitlab
         shell: bash
         env:
          gitlabuser: ${{ secrets.GITLAB_USER }}
          gitlabpwd: ${{ secrets.GITLAB_PWD }}
          gitlabrepo: ${{ secrets.GITLAB_REPO_APP }}
         run: |
              export GIT_SSL_NO_VERIFY=1
              rm -Rf SME-Limpeza-App
              git -c credential.helper='!f() { sleep 1; echo "username=$gitlabuser"; echo "password=$gitlabpwd"; }; f' clone $gitlabrepo -b main
              cd SME-Limpeza-App
              chmod +x menu-run.sh
              echo 2 | ./menu-run.sh
