name: SME-Limpeza-BackEnd
 
on:

  workflow_dispatch:

jobs:
         
  build:

    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      
      -  name: Gitlab
         with:
          username: ${{ secrets.GITLAB_USER }}
          password: ${{ secrets.GITLAB_PWD }}
          repository: ${{ secrets.GITLAB_REPO }}
          run: |
              git -c credential.helper='!f() { sleep 1; echo "username=${{ secrets.GITLAB_USER }}"; echo "password=${{ secrets.GITLAB_PWD }}"; }; f' clone ${{ secrets.GITLAB_REPO }} -b main
              cd SME-Limpeza-BackEnd
              ls
              pwd
      
      -  name: Login to registry
         uses: docker/login-action@v1
         with:
          registry: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PWD }}
    
      - name: Build the Docker image    
        run: |
             docker login ${{ secrets.REGISTRY_HOST }}
             docker build . --tag ${{ secrets.REGISTRY_HOST }}/${GITHUB_REF##*/}/limpeza-backend
             docker push ${{ secrets.REGISTRY_HOST }}/${GITHUB_REF##*/}/limpeza-backend
             
  deploy:
  
    runs-on: self-hosted
    needs: [ build ]
    environment:
      name: production
    steps:
      - name: Redeploy
        uses: luizhpriotto/action_images@kubectl-v2.0
        env: 
          RANCHER_URL: ${{ secrets.RANCHER_URL }}
          RANCHER_TOKEN: ${{ secrets.RANCHER_TOKEN }}
          NAMESPACE: sme-limpeza
