name: SME-Limpeza-BackEnd
 
on:

  workflow_dispatch:

jobs:
         
  build:

    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      
      -  name: Gitlab
         shell: bash
         env:
          gitlabuser: ${{ secrets.GITLAB_USER }}
          gitlabpwd: ${{ secrets.GITLAB_PWD }}
          gitlabrepo: ${{ secrets.GITLAB_REPO }}
         run: |
              git -c credential.helper='!f() { sleep 1; echo "username=$gitlabuser"; echo "password=$gitlabpwd"; }; f' clone $gitlabrepo -b development
      
      -  name: Login to registry
         uses: docker/login-action@v1
         with:
          registry: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PWD }}
    
      - name: Build the Docker image Backend  
        run: |
             cd SME-Limpeza-BackEnd
             docker login ${{ secrets.REGISTRY_HOST }}
             docker build . --tag ${{ secrets.REGISTRY_HOST }}/development/limpeza-backend
             docker push ${{ secrets.REGISTRY_HOST }}/development/limpeza-backend
             
  deploy:
  
    runs-on: self-hosted
    needs: [ build ]
    environment:
      name: development
    steps:
      - name: Redeploy
        uses: luizhpriotto/action_images@kubectl-v2.0
        env: 
          RANCHER_URL: ${{ secrets.RANCHER_URL }}
          RANCHER_TOKEN: ${{ secrets.RANCHER_TOKEN }}
          NAMESPACE: sme-limpeza
