name: SME-Serap-Itens-Api
 
on:

  workflow_dispatch:

jobs:
         
  build-dev:

    runs-on: self-hosted
    if: ${{ github.ref == 'refs/heads/dev' }}
    steps:
      - uses: actions/checkout@v2
      
      -  name: Github
         shell: bash
         env:
          gituser: ${{ secrets.GIT_USER }}
          gittoken: ${{ secrets.GIT_TOKEN }}
         run: |
              git clone https://$gituser:$gittoken@github.com/julianocm/SME-Prova-Serap-Item-Api.git --branch=develop
      
      -  name: Login to registry
         uses: docker/login-action@v1
         with:
          registry: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PWD }}
    
      - name: Build the Docker image Backend  
        run: |
             cd SME-Prova-Serap-Item-Api
             docker login ${{ secrets.REGISTRY_HOST }}
             ls -ltra
             docker build -f src/SME.SERAp.Prova.Item.Api/Dockerfile --tag ${{ secrets.REGISTRY_HOST }}/develop/serap-itens-api .
             docker push ${{ secrets.REGISTRY_HOST }}/develop/serap-itens-api

  flyway-dev:
  
    runs-on: self-hosted
    if: ${{ github.ref == 'refs/heads/dev' }}
    needs: [ build-dev ]       
    environment:
      name: development
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Executando Scripts
        env:
          USER_DB: ${{ secrets.SERAP_ITEN_USER_DB }}
          PASSWORD_DB: ${{ secrets.SERAP_ITEN_PASSWORD_DB }}
          URL_DB: ${{ secrets.SERAP_ITEN_URL_DB }}
        run: docker run --rm -v $PWD/scripts:/flyway/sql boxfuse/flyway:5.2.4 -user=$USER_DB -password=$PASSWORD_DB -url=$URL_DB -outOfOrder=true migrate

  deploy-dev:
  
    runs-on: self-hosted
    needs: [ flyway-dev ]
    if: ${{ github.ref == 'refs/heads/dev' }}
    environment:
      name: development
    steps:
      - name: Redeploy
        uses: luizhpriotto/action_images@kubectl-v2.0
        env: 
          RANCHER_URL: ${{ secrets.RANCHER_URL }}
          RANCHER_TOKEN: ${{ secrets.RANCHER_TOKEN }}
          WORKLOAD: serap-itens-api
          NAMESPACE: sme-serap-itens
